apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress

    spec:
      containers:
        - name: stress
          image: braindeamon/stress
          ports:
            - containerPort: 8084
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"